version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    environment:               
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 
 
  app:
    build: .
    restart: always
    ports:
      - '4001:4001'
    depends_on:
      - db
     

    volumes:
      - mongo-data:/app
  
  
volumes:
  mongo-data:             # Asegúrate de definir el volumen aquí
