version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    environment:               
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  app:
    build: .
    restart: always
    ports:
      - '4001:4001'
    depends_on:
      - db
      -  redis

    volumes:
      - mongo-data:/app
  
  mongo-seed:
    image: mongo:latest
    depends_on:
      - db
    volumes:
      - ./jugadores.json:/jugadores.json
    entrypoint: >
      bash -c "mongoimport --host db --db test --collection Jugadores --authenticationDatabase admin --username root --password example --file /jugadores.json --jsonArray"

volumes:
  mongo-data:             # Asegúrate de definir el volumen aquí
